server:
  servlet:
    context-path: /
    session:
      timeout: 30m
      tracking-modes: cookie
  encoding:
    charset: UTF-8
    enabled: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/together_sports_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: admin1
    password: 1234

  http:
    encoding:
      charset:
        utf-8 force: true

  jwt:
    secret: abcabc

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  # Thymeleaf 설정
  thymeleaf:
    cache: false #template 수정 시 자동 프로젝트 재시작해주어 Test 수행 시 용이하다. (운영 시 true)
    prefix: file:src/main/resources/templates/

  # 파일 경로 설정
  file:
    upload:
      location: 'C:\files'

  # multipart 설정

