spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5638a1ebad37df7a20b7a4e6e280ce63
            client-secret: rq7ZOvgXE2duGZ9rTdREjG86DApPuiOn
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, account_email
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # Authorization Code 받는 주소
            token-uri: https://kauth.kakao.com/oauth/token # Access Token 받는 주소
            user-info-uri: https://kapi.kakao.com/v2/user/me # 계정 정보 받는 주소
            user-name-attribute: id # 계정 정보 데이터를 가져오는 key 값

app:
  oauth2:
    authorized-redirect-uri: http://localhost:3000/auth/saving