spring:

  h2:
    console.enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

  profiles:
    include: oauth2, jwt, storage

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

# aws properties

---
spring:
  profiles:
    active: deployment














