GET http://localhost:8080/api/user
#Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaXNzIjoidG9nZXRoZXItc3BvcnRzIiwiZXhwIjoxNjQ4NzE1MDY5LCJyb2xlIjoiUk9MRV9VU0VSIiwiZW1haWwiOiJqZW9uc2V1bjAwMDBAZ21haWwuY29tIn0.JMYlBuyVRvmVzsA_6pYPGogPQMdGwAYtWo8h7aJQ4rY

###