# default application setting
# encoding properties
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

# spring properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/together_sports_db?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  profiles:
    include: security

# together sports application properties
app:
  storage:
    root: /Users/chayeongho
    location: /Users/chayeongho
  user:
    default-image: https://together-sports.com/images/default_user_profile.jpeg
  room:
    default-image:
      etc: https://together-sports.com/imgaes/default_room_image.png
