# development environment application setting
# spring properties
spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# together sports application properties
app:
  storage:
    root: /Users/seunjeon/Workspace/images
    location: /images