spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5638a1ebad37df7a20b7a4e6e280ce63
            client-secret: rq7ZOvgXE2duGZ9rTdREjG86DApPuiOn
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, account_email
            client-name: Kakao

          google:
            client-id: 96223095074-gf26tnpoii6102hdraiqqmiff5ftpqlv.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
              -
          naver:
            client-id: LA8L8hj5X9Dn1rBjNMOa
            client-secret: RJFDTSMbjm
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: name, email
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # Authorization Code 받는 주소
            token-uri: https://kauth.kakao.com/oauth/token # Access Token 받는 주소
            user-info-uri: https://kapi.kakao.com/v2/user/me # 계정 정보 받는 주소
            user-name-attribute: id # 계정 정보 데이터를 가져오는 key 값
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

app:
  oauth2:
    authorized-redirect-uri: http://localhost:3000/oauth/saving