# aws deployment environment application setting

# https setting
server:
  port: 8443
  ssl:
    key-store: /home/ubuntu/spring-ssl/keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: ts

# spring properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/togethersports?serverTimezone=Asia/Seoul
    username: tsadmin
    password: 1234

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

# together sports application properties
app:
  storage:
    root: /home/ubuntu/together-sports-data
    location: /images

  user:
    default-image: /images/default_user_profile.jpeg
  room:
    default-image:
      etc: /images/default_room_image.png
  room-default-images:
    soccer: /images/default_soccer_room_image.png
    golf: /images/default_golf_room_image.png
    fishing: /images/default_fishing_room_image.png
    baseball: /images/default_baseball_room_image.png
    hiking: /images/default_hiking_room_image.png
    bicycle: /images/default_bicycle_room_image.png
    billiards: /images/default_billiards_room_image.png
    gym: /images/default_gym_room_image.png
    running: /images/default_running_image.png
    ping-pong: /images/default_ping-pong_room_image.png
    basketball: /images/default_basketball_room_image.png
    badminton: /images/default_badminton_room_image.png
    etc: /images/default_etc_room_image.png

