spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_OAUTH2_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH2_CLIENT_SECRET}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: ${HOST}/login/oauth2/code/kakao # env
            scope: profile_nickname, account_email
            client-name: Kakao

          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            redirect-uri: ${HOST}/login/oauth2/code/google
            scope:
              - profile
              - email

          naver:
            client-id: ${NAVER_OAUTH2_CLIENT_ID}
            client-secret: ${NAVER_OAUTH2_CLIENT_SECRET}
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: ${HOST}/login/oauth2/code/naver # env
            scope: name, email
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # Authorization Code 받는 주소
            token-uri: https://kauth.kakao.com/oauth/token # Access Token 받는 주소
            user-info-uri: https://kapi.kakao.com/v2/user/me # 계정 정보 받는 주소
            user-name-attribute: id # 계정 정보 데이터를 가져오는 key 값
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

app:
  oauth2:
    authorized-redirect-uri: ${HOST}/oauth/saving

jwt:
  access-token-signing-key: KWJ0fT7c7yeq6cPCAcikky1U+eRiXeqkStV3ZhkMkWE=
  refresh-token-signing-key : Hh8NL4t1ZMXqc8xkKYS3vFp9b3OvNYy3e7CWSmm5ypU=
  access-token-expiration-time: 30 # 분단위
  refresh-token-expiration-time: 15 # 일단위